language: java
sudo: true
install: true


addons:
  sonarcloud:
    organization: "nicolasba-github"
    token:
      secure: "18a54de57ae21f06658b9532594b2823a2532047"


jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nicolasba-github -Dsonar.login=18a54de57ae21f06658b9532594b2823a2532047 -Dsonar.branch=master       
  - bash infer.sh
  - infer run -- ./gradlew build
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
